[[protocols]]
name = "WD Mini"
protocol = "nec"
variant = "necx"
[protocols.scancodes]
0x847912 = "KEY_ENTER"
0x847906 = "KEY_HOME"
0x847908 = "KEY_UP"
0x847905 = "KEY_RIGHT"
0x847900 = "KEY_DOWN"
0x847907 = "KEY_ENTER"
0x847909 = "KEY_RIGHT"
0x84791b = "KEY_BACK"
0x847904 = "KEY_STOP"
0x84791a = "KEY_OPTION"
0x84791f = "KEY_REWIND"
0x84790a = "KEY_PLAY"
0x84791e = "KEY_FASTFORWARD"
0x847902 = "KEY_PREVIOUS"
0x847901 = "KEY_NEXT"
0x84790f = "KEY_SEARCH"
0x847910 = "KEY_EJECTCD"
